# Copyright 2015 victorusu
# See the top-level LICENSE file for details.
#
# SPDX-License-Identifier: BSD-3-Clause

name: $name
store: /user-environment
description: $descr
spack:
  repo: https://github.com/spack/spack.git
  commit: $spack
modules: false