$envname:
  compiler:
  - toolchain: gcc
    spec: $gcc
  unify: when_possible
  specs:
  - $name $spec
  mpi:
    spec: cray-mpich
  variants:
  - +mpi
  views:
    develop:
      exclude: ['$name']
    $envname:
      link: run
    default:
      link: run